version: '3.8'
services:
  next-app:
    image: mcr.microsoft.com/devcontainers/typescript-node:18
    network_mode: service:db
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
  db:
    image: amazon/dynamodb-local
    container_name: dynamodb
    hostname: dynamodb
    restart: unless-stopped
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  db-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - AWS_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DYNAMO_ENDPOINT=http://db:8000
